sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shawnschembri/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shawnschembri/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-487634826144"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secret: "$AWS_SECRET_KEY"
    